name: user_repository
description: A starting point for Dart libraries or applications.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  domain_models:
    path: ../domain_models

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
